version: 2
updates:
  - assignees:
      - danmaq
    directory: /
    labels:
      - dependencies
    package-ecosystem: npm
    reviewers:
      - danmaq
    schedule:
      interval: monthly
registries:
  npm-github:
    token: ${{ secrets.NPM_TOKEN }}
    type: npm-registry
    url: https://registry.npmjs.org
