env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
  - react
  - react-hooks
rules:
  '@typescript-eslint/explicit-function-return-type':
    - 'off'
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - static.config.js
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  react/prop-types:
    - 'off'
settings:
  import/resolver:
    typescript:
      directory: .
