cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
ignorePaths:
  - src/intl/locales/**
import:
  - '@kurone-kito/cspell-config'
version: '0.2'
words:
  - danmaq
