name: The CI workflow on push the feature branch
on:
  push:
    branches:
      - '*'
      - '!master'
permissions:
  contents: read
jobs:
  build:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
      - name: Stages the pushed branch
        uses: actions/checkout@v2
      - name: Use the specified version of Node.js
        uses: actions/setup-node@v2
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version-file: .node-version
      - name: set npm config
        run: npm config set unsafe-perm true
      - name: Resolve the dependencies
        run: npm ci
      - run: npm run build
      - run: npm run bundle
      - run: npm run export
      - run: npm run lint
